# 1. Importação das bibliotecas

In [1]:
import pandas as pd
import numpy as np

# 2. Carregamento da base RAIS 2025

In [43]:
from google.colab import files

uploaded = files.upload()

arquivo = list(uploaded.keys())[0]

df = pd.read_excel(arquivo)

df_original = df.copy()

print("Arquivo carregado:", arquivo)
print("Quantidade de linhas:", df.shape[0])
print("Quantidade de colunas:", df.shape[1])

Saving RAIS_SJC_354990_Filtrado2(copia).xlsx to RAIS_SJC_354990_Filtrado2(copia) (2).xlsx
Arquivo carregado: RAIS_SJC_354990_Filtrado2(copia) (2).xlsx
Quantidade de linhas: 47339
Quantidade de colunas: 24

# 3. Conhecendo a estrutura da base

In [44]:
print("Dimensões da base:")
print(df.shape)

print("\nNome das colunas:")
print(df.columns.tolist())

print("\nPrimeiras 5 linhas:")
display(df.head())

Dimensões da base:
(47339, 24)

Nome das colunas:
['Bairros SP', 'Bairros Fortaleza', 'Bairros RJ', 'CNAE 2.0 Classe', 'CNAE 95 Classe', 'Distritos SP', 'Qtd Vínculos CLT', 'Qtd Vínculos Ativos', 'Qtd Vínculos Estatutários', 'Ind Atividade Ano', 'Ind CEI Vinculado', 'Ind Estab Participa PAT', 'Ind Rais Negativa', 'Ind Simples', 'Município', 'Natureza Jurídica', 'Regiões Adm DF', 'CNAE 2.0 Subclasse', 'Tamanho Estabelecimento', 'Tipo Estab', 'Tipo Estab.1', 'UF', 'IBGE Subsetor', 'CEP Estab']

Primeiras 5 linhas:

,Bairros SP,Bairros Fortaleza,Bairros RJ,CNAE 2.0 Classe,CNAE 95 Classe,Distritos SP,Qtd Vínculos CLT,Qtd Vínculos Ativos,Qtd Vínculos Estatutários,Ind Atividade Ano,...,Município,Natureza Jurídica,Regiões Adm DF,CNAE 2.0 Subclasse,Tamanho Estabelecimento,Tipo Estab,Tipo Estab.1,UF,IBGE Subsetor,CEP Estab
0,9997,9997,9997,93131,92614,9997,3,3,0,1,...,354990,2062,9997,9313100,2,1,Cnpj,35,21,12231675
1,9997,9997,9997,47440,52442,9997,3,3,0,1,...,354990,2062,9997,4744005,2,1,Cnpj,35,16,12231010
2,9997,9997,9997,56112,55212,9997,6,6,0,1,...,354990,2062,9997,5611205,3,1,Cnpj,35,21,12240540
3,9997,9997,9997,23303,26301,9997,14,14,0,1,...,354990,2062,9997,2330302,4,1,Cnpj,35,2,12238430
4,9997,9997,9997,45307,50300,9997,5,5,0,1,...,354990,2135,9997,4530703,3,1,Cnpj,35,16,12216550

# 4. Tratamento de valores ausentes

In [45]:
nulos = df.isnull().sum()

print("Valores ausentes por coluna:")
print(nulos)

print("\nTotal de valores ausentes na base:", nulos.sum())

Valores ausentes por coluna:
Bairros SP                   0
Bairros Fortaleza            0
Bairros RJ                   0
CNAE 2.0 Classe              0
CNAE 95 Classe               0
Distritos SP                 0
Qtd Vínculos CLT             0
Qtd Vínculos Ativos          0
Qtd Vínculos Estatutários    0
Ind Atividade Ano            0
Ind CEI Vinculado            0
Ind Estab Participa PAT      0
Ind Rais Negativa            0
Ind Simples                  0
Município                    0
Natureza Jurídica            0
Regiões Adm DF               0
CNAE 2.0 Subclasse           0
Tamanho Estabelecimento      0
Tipo Estab                   0
Tipo Estab.1                 0
UF                           0
IBGE Subsetor                0
CEP Estab                    0
dtype: int64

Total de valores ausentes na base: 0

In [46]:
print("Colunas com valores ausentes:")

colunas_com_nulos = nulos[nulos > 0]

if len(colunas_com_nulos) == 0:
    print("Não existem valores ausentes na base.")
else:
    print(colunas_com_nulos)

Colunas com valores ausentes:
Não existem valores ausentes na base.

# 5. Identificação de registros duplicados

In [47]:
duplicadas = df.duplicated(keep=False)

print("Total de registros:", len(df))
print("Registros envolvidos em duplicidades:", duplicadas.sum())
print("Registros únicos:", df.drop_duplicates().shape[0])
print("Registros excedentes caso as duplicidades exatas fossem removidas:",
      len(df) - df.drop_duplicates().shape[0])

Total de registros: 47339
Registros envolvidos em duplicidades: 7906
Registros únicos: 42362
Registros excedentes caso as duplicidades exatas fossem removidas: 4977

# 6. Análise das duplicidades

In [48]:
df["Duplicata_Exata"] = df.duplicated(keep=False)

df_duplicatas = df[df["Duplicata_Exata"]].copy()

print("Registros envolvidos em duplicidades exatas:", len(df_duplicatas))

Registros envolvidos em duplicidades exatas: 7906

In [29]:
df_duplicatas.head(20)

,Bairros SP,Bairros Fortaleza,Bairros RJ,CNAE 2.0 Classe,CNAE 95 Classe,Distritos SP,Qtd Vínculos CLT,Qtd Vínculos Ativos,Qtd Vínculos Estatutários,Ind Atividade Ano,...,Natureza Jurídica,Regiões Adm DF,CNAE 2.0 Subclasse,Tamanho Estabelecimento,Tipo Estab,Tipo Estab.1,UF,IBGE Subsetor,CEP Estab,Duplicata_Exata
5,9997,9997,9997,47547,52434,9997,1,1,0,1,...,2062,9997,4754701,2,1,Cnpj,35,16,12242800,True
16,9997,9997,9997,47121,52132,9997,1,1,0,1,...,2135,9997,4712100,2,1,Cnpj,35,16,12226830,True
24,9997,9997,9997,69206,74128,9997,6,6,0,1,...,2062,9997,6920601,3,1,Cnpj,35,19,12210000,True
43,9997,9997,9997,56112,55220,9997,4,4,0,1,...,2062,9997,5611203,2,1,Cnpj,35,21,12243000,True
69,9997,9997,9997,56112,55220,9997,3,3,0,1,...,2062,9997,5611203,2,1,Cnpj,35,21,12235050,True
76,9997,9997,9997,82199,74993,9997,1,1,0,1,...,2062,9997,8219999,2,1,Cnpj,35,19,12246000,True
87,9997,9997,9997,86305,85138,9997,2,2,0,1,...,2062,9997,8630503,2,1,Cnpj,35,22,12246190,True
92,9997,9997,9997,47814,52329,9997,6,6,0,1,...,2062,9997,4781400,3,1,Cnpj,35,16,12242800,True
99,9997,9997,9997,1512,999,9997,1,1,0,1,...,4120,9997,151202,2,5,Caepf,35,25,12210010,True
135,9997,9997,9997,78205,74500,9997,0,0,0,1,...,2062,9997,7820500,1,1,Cnpj,35,19,12210250,True
150,9997,9997,9997,81125,70408,9997,1,1,0,1,...,3085,9997,8112500,2,1,Cnpj,35,19,12245230,True
157,9997,9997,9997,47890,52493,9997,3,3,0,1,...,2062,9997,4789001,2,1,Cnpj,35,16,12235050,True
158,9997,9997,9997,56112,55220,9997,3,3,0,1,...,2062,9997,5611203,2,1,Cnpj,35,21,12230000,True
170,9997,9997,9997,55108,55131,9997,3,3,0,1,...,2062,9997,5510801,2,1,Cnpj,35,21,12245031,True
171,9997,9997,9997,82113,74993,9997,0,0,0,1,...,2062,9997,8211300,1,1,Cnpj,35,19,12246870,True
176,9997,9997,9997,41107,70106,9997,0,0,0,1,...,2062,9997,4110700,1,1,Cnpj,35,19,12244260,True
209,9997,9997,9997,81125,70408,9997,3,3,0,1,...,3085,9997,8112500,2,1,Cnpj,35,19,12243740,True
210,9997,9997,9997,47814,52329,9997,6,6,0,1,...,2062,9997,4781400,3,1,Cnpj,35,16,12230000,True
231,9997,9997,9997,47211,52221,9997,4,4,0,1,...,2062,9997,4721104,2,1,Cnpj,35,16,12216580,True
238,9997,9997,9997,47814,52329,9997,0,0,0,1,...,2062,9997,4781400,1,1,Cnpj,35,16,12230000,True

In [30]:
contagem_duplicatas = (
    df_duplicatas
    .groupby(
        [col for col in df.columns if col != "Duplicata_Exata"],
        dropna=False
    )
    .size()
    .reset_index(name="Quantidade")
    .sort_values("Quantidade", ascending=False)
)

contagem_duplicatas.head(20)

,Bairros SP,Bairros Fortaleza,Bairros RJ,CNAE 2.0 Classe,CNAE 95 Classe,Distritos SP,Qtd Vínculos CLT,Qtd Vínculos Ativos,Qtd Vínculos Estatutários,Ind Atividade Ano,...,Natureza Jurídica,Regiões Adm DF,CNAE 2.0 Subclasse,Tamanho Estabelecimento,Tipo Estab,Tipo Estab.1,UF,IBGE Subsetor,CEP Estab,Quantidade
2281,9997,9997,9997,85996,80993,9997,0,0,0,0,...,2062,9997,8599604,1,1,Cnpj,35,23,12246000,46
1012,9997,9997,9997,64620,74144,9997,0,0,0,0,...,2062,9997,6462000,1,1,Cnpj,35,19,12242000,25
2541,9997,9997,9997,86305,85138,9997,0,0,0,1,...,2062,9997,8630503,1,1,Cnpj,35,22,12242431,24
88,9997,9997,9997,41107,70106,9997,0,0,0,0,...,2062,9997,4110700,1,1,Cnpj,35,19,12246870,23
81,9997,9997,9997,41107,70106,9997,0,0,0,0,...,2062,9997,4110700,1,1,Cnpj,35,19,12246000,18
316,9997,9997,9997,47130,52159,9997,0,0,0,0,...,2135,9997,4713004,1,1,Cnpj,35,16,12230470,18
1071,9997,9997,9997,64620,74144,9997,0,0,0,0,...,2062,9997,6462000,1,1,Cnpj,35,19,12246870,18
1669,9997,9997,9997,73190,74403,9997,0,0,0,1,...,2062,9997,7319003,1,1,Cnpj,35,19,12243000,17
59,9997,9997,9997,41107,70106,9997,0,0,0,0,...,2062,9997,4110700,1,1,Cnpj,35,19,12230000,17
144,9997,9997,9997,41204,45217,9997,0,0,0,1,...,9999,9997,4120400,1,6,Cno,35,15,12209904,16
1728,9997,9997,9997,77110,71102,9997,0,0,0,0,...,2232,9997,7711000,1,1,Cnpj,35,19,12244095,15
1056,9997,9997,9997,64620,74144,9997,0,0,0,0,...,2062,9997,6462000,1,1,Cnpj,35,19,12246000,15
1115,9997,9997,9997,64638,65994,9997,0,0,0,0,...,2062,9997,6463800,1,1,Cnpj,35,18,12246870,14
1661,9997,9997,9997,73190,74403,9997,0,0,0,1,...,2062,9997,7319002,1,1,Cnpj,35,19,12243000,13
1372,9997,9997,9997,69117,74110,9997,0,0,0,1,...,2321,9997,6911701,1,1,Cnpj,35,19,12246190,13
1189,9997,9997,9997,68102,70106,9997,0,0,0,0,...,2062,9997,6810201,1,1,Cnpj,35,19,12246000,12
1367,9997,9997,9997,69117,74110,9997,0,0,0,1,...,2321,9997,6911701,1,1,Cnpj,35,19,12245820,12
1198,9997,9997,9997,68102,70106,9997,0,0,0,0,...,2062,9997,6810201,1,1,Cnpj,35,19,12246870,12
99,9997,9997,9997,41107,70106,9997,0,0,0,1,...,2062,9997,4110700,1,1,Cnpj,35,19,12246870,12
1682,9997,9997,9997,73190,74403,9997,0,0,0,1,...,2135,9997,7319002,1,1,Cnpj,35,19,12243000,12

# 7. Análise da RAIS negativa

In [31]:
pd.crosstab(
    df["Ind Rais Negativa"],
    df["Duplicata_Exata"]
)

Duplicata_Exata    False  True
Ind Rais Negativa
0                  15508   1308
1                  23876   6594
2                     49      4

In [32]:
analise_rais_negativa = (
    df.groupby(
        ["Ind Rais Negativa", "Duplicata_Exata"]
    )
    .size()
    .reset_index(name="Quantidade")
)

analise_rais_negativa

   Ind Rais Negativa  Duplicata_Exata  Quantidade
0                  0            False       15508
1                  0             True        1308
2                  1            False       23876
3                  1             True        6594
4                  2            False          49
5                  2             True           4

# 8. Análise dos vínculos empregatícios

In [33]:
df.groupby(
    "Qtd Vínculos CLT"
).size().sort_values(ascending=False).head(20)

Qtd Vínculos CLT
0     32281
1      4210
2      2174
3      1479
4      1102
5       826
6       717
7       520
8       443
9       340
10      279
11      217
12      193
13      177
14      153
15      143
16      137
18       99
17       94
19       92
dtype: int64

In [34]:
df["Qtd Vínculos CLT"].describe()

count    47339.000000
mean         4.364815
std         57.253700
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max       8884.000000
Name: Qtd Vínculos CLT, dtype: float64

# 9. Validação dos códigos

In [35]:
for coluna in df.columns:
    quantidade = (df[coluna] == 9997).sum()

    if quantidade > 0:
        print(f"{coluna}: {quantidade}")

Bairros SP: 47339
Bairros Fortaleza: 47339
Bairros RJ: 47339
Distritos SP: 47339
Regiões Adm DF: 47339

# 10. Validação dos estabelecimentos

In [36]:
df["Tipo Estab.1"].value_counts(dropna=False)

Tipo Estab.1
Cnpj                    46244
Caepf                     708
Cno                       387
Name: count, dtype: int64

In [37]:
df["Tipo Estab"].value_counts(dropna=False)

Tipo Estab
1    46244
5      708
6      387
Name: count, dtype: int64

# 11. Definição dos critérios de limpeza

Foram identificados registros com duplicidade exata considerando todas as variáveis disponíveis na base.

Entretanto, a duplicidade das variáveis disponíveis não permite afirmar que os registros representam o mesmo estabelecimento, pois a base analisada não apresenta um identificador único do estabelecimento.

Dessa forma, as duplicidades exatas foram identificadas e analisadas, mas não serão excluídas automaticamente. Essa decisão evita a remoção indevida de registros que podem representar estabelecimentos distintos com características iguais nas variáveis disponíveis.

Os critérios de limpeza serão aplicados somente aos registros que apresentarem inconsistências identificáveis nos dados.

In [11]:
df_duplicatas.head(20)

,Bairros SP,Bairros Fortaleza,Bairros RJ,CNAE 2.0 Classe,CNAE 95 Classe,Distritos SP,Qtd Vínculos CLT,Qtd Vínculos Ativos,Qtd Vínculos Estatutários,Ind Atividade Ano,...,Natureza Jurídica,Regiões Adm DF,CNAE 2.0 Subclasse,Tamanho Estabelecimento,Tipo Estab,Tipo Estab.1,UF,IBGE Subsetor,CEP Estab,Duplicata_Exata
5,9997,9997,9997,47547,52434,9997,1,1,0,1,...,2062,9997,4754701,2,1,Cnpj,35,16,12242800,True
16,9997,9997,9997,47121,52132,9997,1,1,0,1,...,2135,9997,4712100,2,1,Cnpj,35,16,12226830,True
24,9997,9997,9997,69206,74128,9997,6,6,0,1,...,2062,9997,6920601,3,1,Cnpj,35,19,12210000,True
43,9997,9997,9997,56112,55220,9997,4,4,0,1,...,2062,9997,5611203,2,1,Cnpj,35,21,12243000,True
69,9997,9997,9997,56112,55220,9997,3,3,0,1,...,2062,9997,5611203,2,1,Cnpj,35,21,12235050,True
76,9997,9997,9997,82199,74993,9997,1,1,0,1,...,2062,9997,8219999,2,1,Cnpj,35,19,12246000,True
87,9997,9997,9997,86305,85138,9997,2,2,0,1,...,2062,9997,8630503,2,1,Cnpj,35,22,12246190,True
92,9997,9997,9997,47814,52329,9997,6,6,0,1,...,2062,9997,4781400,3,1,Cnpj,35,16,12242800,True
99,9997,9997,9997,1512,999,9997,1,1,0,1,...,4120,9997,151202,2,5,Caepf,35,25,12210010,True
135,9997,9997,9997,78205,74500,9997,0,0,0,1,...,2062,9997,7820500,1,1,Cnpj,35,19,12210250,True
150,9997,9997,9997,81125,70408,9997,1,1,0,1,...,3085,9997,8112500,2,1,Cnpj,35,19,12245230,True
157,9997,9997,9997,47890,52493,9997,3,3,0,1,...,2062,9997,4789001,2,1,Cnpj,35,16,12235050,True
158,9997,9997,9997,56112,55220,9997,3,3,0,1,...,2062,9997,5611203,2,1,Cnpj,35,21,12230000,True
170,9997,9997,9997,55108,55131,9997,3,3,0,1,...,2062,9997,5510801,2,1,Cnpj,35,21,12245031,True
171,9997,9997,9997,82113,74993,9997,0,0,0,1,...,2062,9997,8211300,1,1,Cnpj,35,19,12246870,True
176,9997,9997,9997,41107,70106,9997,0,0,0,1,...,2062,9997,4110700,1,1,Cnpj,35,19,12244260,True
209,9997,9997,9997,81125,70408,9997,3,3,0,1,...,3085,9997,8112500,2,1,Cnpj,35,19,12243740,True
210,9997,9997,9997,47814,52329,9997,6,6,0,1,...,2062,9997,4781400,3,1,Cnpj,35,16,12230000,True
231,9997,9997,9997,47211,52221,9997,4,4,0,1,...,2062,9997,4721104,2,1,Cnpj,35,16,12216580,True
238,9997,9997,9997,47814,52329,9997,0,0,0,1,...,2062,9997,4781400,1,1,Cnpj,35,16,12230000,True

# 12. Aplicação da limpeza

In [49]:
df_limpo = df.copy()

print("Registros antes da limpeza:", len(df))
print("Registros depois da limpeza:", len(df_limpo))
print("Registros removidos:", len(df) - len(df_limpo))

Registros antes da limpeza: 47339
Registros depois da limpeza: 47339
Registros removidos: 0

# 13. Validação da base final

In [50]:
print("=== VALIDAÇÃO DA BASE FINAL ===")

print("Registros na base original:", len(df_original))
print("Registros na base final:", len(df_limpo))
print("Registros removidos:", len(df_original) - len(df_limpo))

print("\nValores ausentes na base final:")
print(df_limpo.isnull().sum().sum())

print("\nDuplicidades exatas na base final:")
print(df_limpo.duplicated(keep=False).sum())

=== VALIDAÇÃO DA BASE FINAL ===
Registros na base original: 47339
Registros na base final: 47339
Registros removidos: 0

Valores ausentes na base final:
0

Duplicidades exatas na base final:
7906

### Conclusão da validação

A base final permaneceu com 47.339 registros, pois não foram identificados critérios seguros que justificassem a exclusão das duplicidades exatas encontradas.

A análise identificou 7.906 registros envolvidos em duplicidades exatas. Entretanto, a ausência de um identificador único do estabelecimento impede afirmar que esses registros representam necessariamente erros ou repetições indevidas.

Também não foram identificados valores ausentes na base. Dessa forma, a base foi mantida integralmente, preservando os registros para as etapas posteriores de análise.

# 14. Exportação da base limpa

In [51]:
arquivo_saida = "RAIS_2025_SJC_limpa.xlsx"

df_limpo.to_excel(
    arquivo_saida,
    index=False
)

print("Arquivo exportado:", arquivo_saida)

Arquivo exportado: RAIS_2025_SJC_limpa.xlsx

In [52]:
files.download(arquivo_saida)

In [53]:
import os

print("Arquivo existe:", os.path.exists(arquivo_saida))

if os.path.exists(arquivo_saida):
    tamanho_mb = os.path.getsize(arquivo_saida) / (1024 * 1024)
    print(f"Tamanho do arquivo: {tamanho_mb:.2f} MB")

Arquivo existe: True
Tamanho do arquivo: 3.98 MB